import { formatCurrency } from "@/utils/currency";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import type { HistoryItem } from "../context";

import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

export type ExportLanguage = "pt" | "en" | "es";

type ExportLabels = {
  title: string;
  subtitle: string;
  issuedAt: string;
  summary: string;
  totalAnalyses: string;
  averageConsumption: string;
  predominantProfile: string;
  averageMonthlyCost: string;
  monthlyCost: string;
  insights: string;
  date: string;
  category: string;
  consumption: string;
  reportFooter: string;
  historySheet: string;
  efficient: string;
  moderate: string;
  inefficient: string;
  none: string;
};

const translations: Record<ExportLanguage, ExportLabels> = {
  pt: {
    title: "Relatório de Consumo Energético",
    subtitle: "Sistema Inteligente de Monitoramento Energético",
    issuedAt: "Emitido em",
    summary: "Resumo",
    totalAnalyses: "Total de análises",
    averageConsumption: "Consumo médio",
    predominantProfile: "Perfil predominante",
    averageMonthlyCost: "Custo médio mensal",
    monthlyCost: "Custo estimado mensal",
    insights: "Insights da IA",
    date: "Data",
    category: "Categoria",
    consumption: "Consumo",
    reportFooter: "Relatório gerado automaticamente pelo IntelliWatts",
    historySheet: "Histórico",
    efficient: "Eficiente",
    moderate: "Moderado",
    inefficient: "Ineficiente",
    none: "Nenhum",
  },

  en: {
    title: "Energy Consumption Report",
    subtitle: "Intelligent Energy Monitoring System",
    issuedAt: "Issued on",
    summary: "Summary",
    totalAnalyses: "Total analyses",
    averageConsumption: "Average consumption",
    predominantProfile: "Predominant profile",
    averageMonthlyCost: "Average monthly cost",
    monthlyCost: "Estimated monthly cost",
    insights: "AI Insights",
    date: "Date",
    category: "Category",
    consumption: "Consumption",
    reportFooter: "Report automatically generated by IntelliWatts",
    historySheet: "History",
    efficient: "Efficient",
    moderate: "Moderate",
    inefficient: "Inefficient",
    none: "None",
  },

  es: {
    title: "Informe de Consumo Energético",
    subtitle: "Sistema Inteligente de Monitoreo Energético",
    issuedAt: "Emitido el",
    summary: "Resumen",
    totalAnalyses: "Total de análisis",
    averageConsumption: "Consumo promedio",
    predominantProfile: "Perfil predominante",
    averageMonthlyCost: "Costo mensual promedio",
    monthlyCost: "Costo mensual estimado",
    insights: "Insights de la IA",
    date: "Fecha",
    category: "Categoría",
    consumption: "Consumo",
    reportFooter: "Informe generado automáticamente por IntelliWatts",
    historySheet: "Historial",
    efficient: "Eficiente",
    moderate: "Moderado",
    inefficient: "Ineficiente",
    none: "Ninguno",
  },
};

function calculateExportAnalytics(history: HistoryItem[]) {
  const consumptions = history.map((item) => {
    return Number(
      item.consumo
        .replace("kWh", "")
        .replace(",", ".")
        .trim()
    );
  });

  const totalAnalyses = history.length;

  const averageConsumption =
    consumptions.length > 0
      ? consumptions.reduce(
          (acc, value) => acc + value,
          0
        ) / consumptions.length
      : 0;

  const profiles = history.map(
    (item) => item.perfil
  );

  const profileCount = {
    Eficiente: profiles.filter(
      (profile) => profile === "Eficiente"
    ).length,

    Moderado: profiles.filter(
      (profile) => profile === "Moderado"
    ).length,

    Ineficiente: profiles.filter(
      (profile) => profile === "Ineficiente"
    ).length,
  };

  let predominantProfile:
    | "Eficiente"
    | "Moderado"
    | "Ineficiente"
    | "Nenhum" = "Nenhum";

  if (totalAnalyses > 0) {
    predominantProfile =
      Object.entries(profileCount).sort(
        (a, b) => b[1] - a[1]
      )[0][0] as
        | "Eficiente"
        | "Moderado"
        | "Ineficiente";
  }

  const custoMedioMensal =
    history.length === 0
      ? 0
      : history.reduce(
          (acc, item) => acc + item.custoEstimadoMensal,
          0
        ) / history.length;

  return {
    totalAnalyses,
    averageConsumption,
    predominantProfile,
    custoMedioMensal,

    highestConsumption:
      consumptions.length > 0
        ? Math.max(...consumptions)
        : 0,

    lowestConsumption:
      consumptions.length > 0
        ? Math.min(...consumptions)
        : 0,
  };
}

function translateProfile(
  profile: string,
  labels: ExportLabels
) {
  switch (profile) {
    case "Eficiente":
      return labels.efficient;

    case "Moderado":
      return labels.moderate;

    case "Ineficiente":
      return labels.inefficient;

    default:
      return labels.none;
  }
}

export function exportToPDF(
  history: HistoryItem[],
  language: ExportLanguage = "pt"
) {
  const labels = translations[language];

  const analytics =
    calculateExportAnalytics(history);

  const doc = new jsPDF();

  // Cabeçalho
  doc.setFillColor(250, 204, 21);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(0);
  doc.setFontSize(22);
  doc.text("IntelliWatts", 14, 15);

  doc.setFontSize(10);
  doc.text(labels.subtitle, 14, 23);

  // Título
  doc.setFontSize(18);
  doc.text(labels.title, 14, 42);

  doc.setFontSize(11);

  doc.text(
    `${labels.issuedAt}: ${new Date().toLocaleDateString(
      language === "pt"
        ? "pt-BR"
        : language === "es"
        ? "es-ES"
        : "en-US"
    )}`,
    14,
    50
  );

  // Resumo
  doc.setFontSize(15);
  doc.text(labels.summary, 14, 65);

  doc.setFontSize(11);

  doc.text(
    `${labels.totalAnalyses}: ${analytics.totalAnalyses}`,
    14,
    74
  );

  doc.text(
    `${labels.averageConsumption}: ${analytics.averageConsumption.toFixed(
      0
    )} kWh`,
    14,
    82
  );

  doc.text(
    `${labels.predominantProfile}: ${translateProfile(
      analytics.predominantProfile,
      labels
    )}`,
    14,
    90
  );

  doc.text(
    `${labels.averageMonthlyCost}: ${formatCurrency(
      analytics.custoMedioMensal
    )}`,
    14,
    98
  );

  // Insights
  doc.setFontSize(15);
  doc.text(labels.insights, 14, 114);

  doc.setFontSize(11);

  let y = 123;

  const insightTexts =
    language === "pt"
      ? [
          `Maior consumo: ${analytics.highestConsumption} kWh.`,
          `Menor consumo: ${analytics.lowestConsumption} kWh.`,
          `Perfil predominante: ${translateProfile(
            analytics.predominantProfile,
            labels
          )}.`,
        ]
      : language === "en"
      ? [
          `Highest consumption: ${analytics.highestConsumption} kWh.`,
          `Lowest consumption: ${analytics.lowestConsumption} kWh.`,
          `Predominant profile: ${translateProfile(
            analytics.predominantProfile,
            labels
          )}.`,
        ]
      : [
          `Mayor consumo: ${analytics.highestConsumption} kWh.`,
          `Menor consumo: ${analytics.lowestConsumption} kWh.`,
          `Perfil predominante: ${translateProfile(
            analytics.predominantProfile,
            labels
          )}.`,
        ];

  insightTexts.forEach((insight) => {
    doc.text(`• ${insight}`, 18, y);
    y += 8;
  });

  // Tabela
  autoTable(doc, {
    startY: y + 10,

    head: [[
      labels.date,
      labels.category,
      labels.consumption,
    ]],

    body: history.map((item) => [
      item.data,
      translateProfile(item.perfil, labels),
      item.consumo,
    ]),
  });

  // Rodapé
  const pageHeight =
    doc.internal.pageSize.height;

  doc.setFontSize(9);
  doc.setTextColor(120);

  doc.text(
    labels.reportFooter,
    14,
    pageHeight - 10
  );

  // Nome do arquivo
  const fileName =
    language === "pt"
      ? "Relatorio_IntelliWatts.pdf"
      : language === "en"
      ? "IntelliWatts_Report.pdf"
      : "Informe_IntelliWatts.pdf";

  doc.save(fileName);
}

export function exportToExcel(
  history: HistoryItem[],
  language: ExportLanguage = "pt"
) {
  const labels = translations[language];

  const data = history.map((item) => ({
    [labels.date]: item.data,

    [labels.category]: translateProfile(
      item.perfil,
      labels
    ),

    [labels.consumption]: item.consumo,

    [labels.monthlyCost]: formatCurrency(
      item.custoEstimadoMensal,
    ),
  }));

  const worksheet =
    XLSX.utils.json_to_sheet(data);

  const workbook =
    XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    labels.historySheet
  );

  const excelBuffer = XLSX.write(
    workbook,
    {
      bookType: "xlsx",
      type: "array",
    }
  );

  const file = new Blob(
    [excelBuffer],
    {
      type:
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }
  );

  const fileName =
    language === "pt"
      ? "Relatorio_IntelliWatts.xlsx"
      : language === "en"
      ? "IntelliWatts_Report.xlsx"
      : "Informe_IntelliWatts.xlsx";

  saveAs(file, fileName);
}