# -*- coding: utf-8 -*-
"""EnergIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4ZK9kA4oPeVhwSU-X2PoyqEQrFWn8yC
"""

from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt


DATASCIENCE_DIR = Path(__file__).resolve().parents[1]

DATASET_ORIGINAL_PATH = (
    DATASCIENCE_DIR
    / "datasets"
    / "consumo_energetico.csv"
)

DATASET_PROCESSADO_PATH = (
    DATASCIENCE_DIR
    / "datasets"
    / "consumo_energetico_processado.csv"
)

MODEL_PATH = DATASCIENCE_DIR / "modelo_energiAI.pkl"

#Configuração para gráficos
plt.style.use("ggplot")

df = pd.read_csv(DATASET_ORIGINAL_PATH)

df.head()

#Informações gerais
df.info()

#Estatísticas descritivas
df.describe()

#Conferindo valores nulos
df.isnull().sum()

#Distribuição das classes
df["categoria"].value_counts()

#Gráfico para mostrar se as classes estão balanceadas
df["categoria"].value_counts().plot(kind="bar")

plt.title("Distribuição das categorias")
plt.xlabel("Categoria")
plt.ylabel("Quantidade")

plt.show()

#Distribuição de consumo
plt.hist(df["consumo_kwh"], bins=30)

plt.title("Distribuição do consumo mensal")
plt.xlabel("kWh")
plt.ylabel("Quantidade")

plt.show()

#Há consumos altos

# Quantidade de equipamentos
plt.hist(df["quantidade_equipamentos"], bins=15)

plt.title("Quantidade de equipamentos")

plt.show()

#Tipo de imóvel
df["tipo_imovel"].value_counts().plot(kind="bar")

plt.title("Tipos de imóvel")

plt.show()

#Horário de pico
df["uso_horario_pico"].value_counts().plot(kind="bar")

plt.title("Uso em horário de pico")

plt.show()

#Consumo por categoria (Importante)
df.boxplot(column="consumo_kwh", by="categoria")

plt.title("Consumo por categoria")
plt.suptitle("")

plt.show()

#Eficiente  ← menor consumo

#Moderado

#Ineficiente ← maior consumo

#Equipamentos por categoria
df.boxplot(column="quantidade_equipamentos", by="categoria")

plt.title("Equipamentos por categoria")
plt.suptitle("")

plt.show()

#Horas de alto consumo
df.boxplot(column="horas_alto_consumo", by="categoria")

plt.title("Horas de alto consumo")
plt.suptitle("")

plt.show()

#Consumo médio por categoria
df.groupby("categoria")["consumo_kwh"].mean()

df.groupby("categoria")["consumo_kwh"].mean().plot(kind="bar")

plt.ylabel("kWh")

plt.title("Consumo médio por categoria")

plt.show()

"""#Conclusão do EDA

1. As categorias apresentam distribuições distintas de consumo.
2. Os consumos mensais são altíssimos
3. A quantidade de equipamentos é alta, quanto mais equipamentos, mais energia gasta.
4. Casa e apartamento estão entre os imóveis com mais gasto de energia.
5. Imóveis classificados como "ineficiente" gastam mais energia.
6. O uso em horário de pico está mais presente nas categorias de maior consumo.

#Engenharia de Atributos
"""

#Índice de consumo por equipamento

#A ideia é medir quanto, em média, cada equipamento representa no consumo.

df["consumo_por_equipamento"] = (
    df["consumo_kwh"] /
    df["quantidade_equipamentos"]
)

df.head()

#Intensidade de consumo
#Essa variável indica quanto de energia é consumida, em média, durante os períodos de maior utilização.

df["intensidade_consumo"] = (
    df["consumo_kwh"] /
    df["horas_alto_consumo"]
)

#Equipamentos por hora
#Ajuda a identificar concentração de uso.

df["equipamentos_por_hora"] = (
    df["quantidade_equipamentos"] /
    df["horas_alto_consumo"]
)

#Transformando booleano em número

df["uso_horario_pico_num"] = (
    df["uso_horario_pico"]
    .astype(int)
)

#True  → 1

#False → 0

df.head()

#Verificando correlações
numericas = df.select_dtypes(include=["number"])

correlacao = numericas.corr()

correlacao

#Visualizando a correlação
plt.figure(figsize=(10,8))

plt.imshow(correlacao, cmap="coolwarm", aspect="auto")

plt.xticks(
    range(len(correlacao.columns)),
    correlacao.columns,
    rotation=90
)

plt.yticks(
    range(len(correlacao.columns)),
    correlacao.columns
)

plt.colorbar()

plt.title("Matriz de Correlação")

plt.show()

#Salvando o dataset processado (para treinar os modelos)
df.to_csv(
    DATASET_PROCESSADO_PATH,
    index=False
)

"""# Pré-processamento e Treinamento dos Modelos"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OneHotEncoder

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

#Carregando o dataset processado
df = pd.read_csv(DATASET_PROCESSADO_PATH)

#Separando X e y
y = df["categoria"]
X = df.drop(columns=["categoria"])

#Dividindo treino e teste (80% para treino)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

#Identificando as colunas categóricas
categoricas = ["tipo_imovel"]

numericas = [
    col for col in X.columns
    if col not in categoricas
]

#Criando o pré-processamento
preprocessador = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categoricas
        )
    ],
    remainder="passthrough"
)

"""##Criando os modelos"""

#Decision tree
pipeline_tree = Pipeline([
    ("preprocessamento", preprocessador),
    ("modelo", DecisionTreeClassifier(random_state=42))
])

#Random forest
pipeline_rf = Pipeline([
    ("preprocessamento", preprocessador),
    ("modelo", RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ))
])

#Regressão logística
pipeline_lr = Pipeline([
    ("preprocessamento", preprocessador),
    ("modelo", LogisticRegression(
        max_iter=1000
    ))
])

"""##Treinando"""

pipeline_tree.fit(X_train, y_train)

pipeline_rf.fit(X_train, y_train)

pipeline_lr.fit(X_train, y_train)

#Fazendo previsões
pred_tree = pipeline_tree.predict(X_test)

pred_rf = pipeline_rf.predict(X_test)

pred_lr = pipeline_lr.predict(X_test)

#Acurácia
print("Decision Tree:", accuracy_score(y_test, pred_tree))

print("Random Forest:", accuracy_score(y_test, pred_rf))

print("Logistic Regression:", accuracy_score(y_test, pred_lr))

#Classification Report
##Random Forest
print(classification_report(
    y_test,
    pred_rf
))

#Matriz de Confusão
print(confusion_matrix(
    y_test,
    pred_rf
))

#Comparação dos modelos
resultado = pd.DataFrame({
    "Modelo": [
        "Decision Tree",
        "Random Forest",
        "Logistic Regression"
    ],
    "Accuracy": [
        accuracy_score(y_test, pred_tree),
        accuracy_score(y_test, pred_rf),
        accuracy_score(y_test, pred_lr)
    ]
})

resultado

"""# Avaliação dos Modelos"""

#Criando uma função para avaliar qualquer modelo

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

def avaliar_modelo(nome, y_true, y_pred):
    print("="*60)
    print(f"Modelo: {nome}")
    print("="*60)

    print(f"Acurácia : {accuracy_score(y_true, y_pred):.4f}")
    print(f"Precisão : {precision_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"Recall   : {recall_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"F1-Score : {f1_score(y_true, y_pred, average='weighted'):.4f}")

    print("\nClassification Report:\n")
    print(classification_report(y_true, y_pred))

    print("\nMatriz de Confusão:\n")
    print(confusion_matrix(y_true, y_pred))

#Avaliando todos os modelos
avaliar_modelo(
    "Decision Tree",
    y_test,
    pred_tree
)

avaliar_modelo(
    "Random Forest",
    y_test,
    pred_rf
)

avaliar_modelo(
    "Logistic Regression",
    y_test,
    pred_lr
)

#Comparando resultados
resultado = pd.DataFrame({
    "Modelo":[
        "Decision Tree",
        "Random Forest",
        "Logistic Regression"
    ],
    "Accuracy":[
        accuracy_score(y_test,pred_tree),
        accuracy_score(y_test,pred_rf),
        accuracy_score(y_test,pred_lr)
    ],
    "F1-Score":[
        f1_score(y_test,pred_tree,average="weighted"),
        f1_score(y_test,pred_rf,average="weighted"),
        f1_score(y_test,pred_lr,average="weighted")
    ]
})

resultado.sort_values(
    by="Accuracy",
    ascending=False
)

"""##Descobrindo qual variável foi mais importante

"""

#pegando o modelo treinado:
modelo_rf = pipeline_rf.named_steps["modelo"]

#recuperando os nomes das colunas após o One-Hot Encoding:
feature_names = pipeline_rf.named_steps[
    "preprocessamento"
].get_feature_names_out()

#Criando um DataFrame
importancias = pd.DataFrame({
    "Variavel": feature_names,
    "Importancia": modelo_rf.feature_importances_
})

importancias = importancias.sort_values(
    by="Importancia",
    ascending=False
)

importancias.head(10)

#Gráfico das importâncias (Quais fatores mais influenciaram a classificação?)
plt.figure(figsize=(10,6))

plt.barh(
    importancias["Variavel"][:10],
    importancias["Importancia"][:10]
)

plt.title("Top 10 Variáveis Mais Importantes")

plt.gca().invert_yaxis()

plt.show()

"""Após comparar os modelos **Decision Tree, Random Forest e Logistic Regression**, o ***Random Forest*** apresentou o melhor desempenho, alcançando maior acurácia e F1-Score.

Além disso, esse algoritmo oferece maior robustez contra overfitting e permite interpretar a importância das variáveis, sendo escolhido como modelo final da aplicação.

#Validação Cruzada (Cross Validation)
"""

from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    pipeline_rf,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Acurácia em cada Fold:")

print(scores)

print()

print(f"Média: {scores.mean():.4f}")

print(f"Desvio Padrão: {scores.std():.4f}")

#Escolhendo o modelo final
modelo_final = pipeline_rf

#Salvando o modelo
import joblib

joblib.dump(
    modelo_final,
    MODEL_PATH
)

modelo = joblib.load(
    MODEL_PATH
)

import pandas as pd

novo_cliente = pd.DataFrame({

    "consumo_kwh":[420],

    "uso_horario_pico":[True],

    "quantidade_equipamentos":[10],

    "tipo_imovel":["Casa"],

    "horas_alto_consumo":[8],

    "consumo_por_equipamento":[42],

    "intensidade_consumo":[52.5],

    "equipamentos_por_hora":[1.25],

    "uso_horario_pico_num":[1],

})

predicao = modelo.predict(novo_cliente)

print(predicao)

prob = modelo.predict_proba(novo_cliente)

print(prob)

classe = predicao[0]

indice = list(modelo.classes_).index(classe)

probabilidade = prob[0][indice]

print(probabilidade)

#Função pronta para a API
def preparar_dados(dados):
    df = pd.DataFrame([dados])

    df["consumo_por_equipamento"] = (
        df["consumo_kwh"] /
        df["quantidade_equipamentos"]
    )

    df["intensidade_consumo"] = (
        df["consumo_kwh"] /
        df["horas_alto_consumo"]
    )

    df["equipamentos_por_hora"] = (
        df["quantidade_equipamentos"] /
        df["horas_alto_consumo"]
    )

    df["uso_horario_pico_num"] = (
        df["uso_horario_pico"]
        .astype(int)
    )

    return df

entrada = {
    "consumo_kwh":420,
    "uso_horario_pico":True,
    "quantidade_equipamentos":10,
    "tipo_imovel":"Casa",
    "horas_alto_consumo":8
}

dados = preparar_dados(entrada)

categoria = modelo.predict(dados)[0]

probabilidade = modelo.predict_proba(dados).max()

print(categoria)

print(probabilidade)

print(modelo.predict_proba(dados))

print(dados)

"""#lógica de negócio"""

joblib.dump(modelo_final, MODEL_PATH)

import joblib
import pandas as pd

# Carrega o modelo salvo
modelo = joblib.load(MODEL_PATH)

# Tarifa de referência do hackathon
TARIFA = 0.75


def preparar_dados(entrada):
    """
    Recebe um dicionário com os dados da residência
    e cria as mesmas variáveis utilizadas no treinamento.
    """

    df = pd.DataFrame([entrada])

    df["consumo_por_equipamento"] = (
        df["consumo_kwh"] /
        df["quantidade_equipamentos"]
    )

    df["intensidade_consumo"] = (
        df["consumo_kwh"] /
        df["horas_alto_consumo"]
    )

    df["equipamentos_por_hora"] = (
        df["quantidade_equipamentos"] /
        df["horas_alto_consumo"]
    )

    df["uso_horario_pico_num"] = (
        df["uso_horario_pico"].astype(int)
    )

    df["score_energetico"] = (
        df["consumo_kwh"] * 0.5 +
        df["quantidade_equipamentos"] * 10 +
        df["horas_alto_consumo"] * 20 +
        df["uso_horario_pico_num"] * 50
    )

    return df


def calcular_custo(consumo_kwh):
    """
    Calcula o custo estimado mensal.
    """
    return round(consumo_kwh * TARIFA, 2)


def gerar_recomendacoes(entrada):
    """
    Gera recomendações com base nos dados informados.
    """

    recomendacoes = []

    if entrada["uso_horario_pico"]:
        recomendacoes.append(
            "Reduzir o uso de equipamentos durante horários de pico."
        )

    if entrada["consumo_kwh"] > 400:
        recomendacoes.append(
            "Avaliar aparelhos com alto consumo energético."
        )

    if entrada["quantidade_equipamentos"] > 10:
        recomendacoes.append(
            "Substituir equipamentos antigos por modelos mais eficientes."
        )

    if entrada["horas_alto_consumo"] > 6:
        recomendacoes.append(
            "Distribuir atividades de maior consumo ao longo do dia."
        )

    if len(recomendacoes) == 0:
        recomendacoes.append(
            "Seu perfil energético apresenta boa eficiência."
        )

    return recomendacoes


def analisar(entrada):
    """
    Executa toda a análise energética.
    """

    dados = preparar_dados(entrada)

    categoria = modelo.predict(dados)[0]

    probabilidades = modelo.predict_proba(dados)[0]

    indice = list(modelo.classes_).index(categoria)

    probabilidade = round(
        float(probabilidades[indice]),
        4
    )

    resultado = {
        "categoria": categoria,
        "probabilidade": probabilidade,
        "custo_estimado_mensal": calcular_custo(
            entrada["consumo_kwh"]
        ),
        "recomendacoes": gerar_recomendacoes(entrada)
    }

    return resultado

entrada = {
    "consumo_kwh": 420,
    "uso_horario_pico": True,
    "quantidade_equipamentos": 10,
    "tipo_imovel": "Casa",
    "horas_alto_consumo": 8
}

resultado = analisar(entrada)

print(resultado)

"""#Cenário 1 — Usuário eficiente"""

entrada = {
    "consumo_kwh": 120,
    "uso_horario_pico": False,
    "quantidade_equipamentos": 4,
    "tipo_imovel": "Apartamento",
    "horas_alto_consumo": 2
}

print(analisar(entrada))

"""#Cenário 2 — Usuário moderado"""

entrada = {
    "consumo_kwh": 320,
    "uso_horario_pico": True,
    "quantidade_equipamentos": 8,
    "tipo_imovel": "Casa",
    "horas_alto_consumo": 5
}

print(analisar(entrada))

"""#Cenário 3 — Usuário ineficiente"""

entrada = {
    "consumo_kwh": 700,
    "uso_horario_pico": True,
    "quantidade_equipamentos": 16,
    "tipo_imovel": "Comércio",
    "horas_alto_consumo": 10
}

print(analisar(entrada))

